// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/metadata.dart';
import 'api/scan.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DataReaderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DataReader
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    dynamic raw,
  );

  @protected
  DataReader
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    dynamic raw,
  );

  @protected
  Map<String, BigInt> dco_decode_Map_String_u_64_None(dynamic raw);

  @protected
  DataReader
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    dynamic raw,
  );

  @protected
  RustStreamSink<ScanProgress> dco_decode_StreamSink_scan_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FolderScanResult dco_decode_box_autoadd_folder_scan_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FolderScanResult dco_decode_folder_scan_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImageInfo dco_decode_image_info(dynamic raw);

  @protected
  ImageScanResult dco_decode_image_scan_result(dynamic raw);

  @protected
  List<ImageScanResult> dco_decode_list_image_scan_result(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FolderScanResult? dco_decode_opt_box_autoadd_folder_scan_result(dynamic raw);

  @protected
  List<ImageScanResult>? dco_decode_opt_list_image_scan_result(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DataReader
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    SseDeserializer deserializer,
  );

  @protected
  DataReader
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, BigInt> sse_decode_Map_String_u_64_None(
    SseDeserializer deserializer,
  );

  @protected
  DataReader
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ScanProgress> sse_decode_StreamSink_scan_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FolderScanResult sse_decode_box_autoadd_folder_scan_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FolderScanResult sse_decode_folder_scan_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImageInfo sse_decode_image_info(SseDeserializer deserializer);

  @protected
  ImageScanResult sse_decode_image_scan_result(SseDeserializer deserializer);

  @protected
  List<ImageScanResult> sse_decode_list_image_scan_result(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FolderScanResult? sse_decode_opt_box_autoadd_folder_scan_result(
    SseDeserializer deserializer,
  );

  @protected
  List<ImageScanResult>? sse_decode_opt_list_image_scan_result(
    SseDeserializer deserializer,
  );

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    DataReader self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    DataReader self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_u_64_None(
    Map<String, BigInt> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    DataReader self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_scan_progress_Sse(
    RustStreamSink<ScanProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_folder_scan_result(
    FolderScanResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_folder_scan_result(
    FolderScanResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_image_info(ImageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_image_scan_result(
    ImageScanResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_image_scan_result(
    List<ImageScanResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_u_64(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_folder_scan_result(
    FolderScanResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_image_scan_result(
    List<ImageScanResult>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDataReader(
    int ptr,
  );
}
