// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_exif`, `extract_nai_data`

String extractMetadata({required List<int> inputBytes}) => RustLib.instance.api
    .crateApiMetadataExtractMetadata(inputBytes: inputBytes);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DataReader>>
abstract class DataReader implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DataReader> newInstance({required List<int> data}) =>
      RustLib.instance.api.crateApiMetadataDataReaderNew(data: data);

  Future<int> readBit();

  Future<int> readByte();

  Future<Uint8List> readBytes({required BigInt n});

  Future<int> readInt32();
}
